[package]
name = "server"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "server"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.8"
hyper = "1.9"
tower = "0.5"
tower-http = { version = "0.6", features = [
    "trace",
    "timeout",
    "request-id",
    "cors",
    "normalize-path",
] }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json", "env-filter"] }

reqwest = { version = "0.13", default-features = false, features = [
    "json",
    "rustls",
] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1", features = ["v7", "serde"] }
dotenvy = "0.15"

anyhow = "1.0"
thiserror = "2"

tokio-postgres = {version = "0.7", features = ["with-chrono-0_4","with-serde_json-1"]}
deadpool-postgres = "0.14"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = 3